// Generated by FlutterFire for project `appxlstore-8519d`.
// To refresh: `dart pub global run flutterfire_cli:flutterfire configure --project=appxlstore-8519d`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'FCM web: añade la app web en Firebase y vuelve a ejecutar flutterfire configure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'FCM solo está pensado para Android/iOS en este proyecto.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASl7Jh4utN28HTdDfrQp4KGjE7-a8nisI',
    appId: '1:53460567987:android:b8c36c8e0bc45cb1f06dc6',
    messagingSenderId: '53460567987',
    projectId: 'appxlstore-8519d',
    storageBucket: 'appxlstore-8519d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWg2pNs6chI6KLaTXvkBINcW-KTaso-l8',
    appId: '1:53460567987:ios:70f5513560a7725af06dc6',
    messagingSenderId: '53460567987',
    projectId: 'appxlstore-8519d',
    storageBucket: 'appxlstore-8519d.firebasestorage.app',
    iosBundleId: 'com.appXLStore',
  );

}