// Generated by FlutterFire for project `appxlstore`.
// To refresh: `dart pub global run flutterfire_cli:flutterfire configure --project=appxlstore`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'FCM web: añade la app web en Firebase y vuelve a ejecutar flutterfire configure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'FCM solo está pensado para Android/iOS en este proyecto.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaz5DQ2JxIP-ay3jJKgHZ69X9TInhsa0U',
    appId: '1:1080841335769:android:8fe3a30815b1ada11e9fc8',
    messagingSenderId: '1080841335769',
    projectId: 'appxlstore',
    storageBucket: 'appxlstore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0lMFhQCaIIGyJZ8rNLzRtdISTfcMRgvU',
    appId: '1:1080841335769:ios:8f2d8c93abde20201e9fc8',
    messagingSenderId: '1080841335769',
    projectId: 'appxlstore',
    storageBucket: 'appxlstore.firebasestorage.app',
    iosBundleId: 'com.appXLStore',
  );

}